runtime: nodejs20

instance_class: F4_1G

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: production
  HOST: 0.0.0.0
  DATABASE_NAME: 'postgres' 
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: 2025@Nuzul
  INSTANCE_CONNECTION_NAME: 'nuzul-app-ed7e0:me-central1:nuzul-strapi'
  GCS_BUCKET_NAME: 'strapi-image-cms'
  GCS_BASE_PATH: 'images'

# Health checks
readiness_check:
  path: "/_health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/_health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
  initial_delay_sec: 300

